# Generated by Django 4.2 on 2024-07-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_brand_current_remove_product_volt_product_current_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='current',
        ),
        migrations.AddField(
            model_name='product',
            name='volt',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='un_branded', max_length=250),
        ),
    ]
