# Generated by Django 4.2 on 2024-07-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_brand_current_remove_product_volt_product_current_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique=True),
        ),
    ]
