# Generated by Django 4.2 on 2024-07-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_brand_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='current',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique=True),
        ),
    ]
